### PR TITLE
Fix the setUpdate call

### PR DESCRIPTION
**Pull request by briandela**
setUpdate was not working due to a small typo. Fixed that.

### CODE REVIEW

**Comment by llacroix** [comment]
Cool thank you.

**Comment by briandela** [comment]
@llacroix Would you be open to pushing a new version to npm? I could add the PR with the updated package.json.

**Comment by llacroix** [comment]
Ah sure I'll do that. I can update it myself unless you made some changes to the package.json other than the version.

**Comment by briandela** [comment]
I haven't made any other changes.

Is there a license for this module like MIT or something else?

**Comment by llacroix** [comment]
There wasn't but I'll add MIT

**Comment by llacroix** [comment]
Published

**Comment by briandela** [comment]
@llacroix awesome - thanks!

**Pull request merged**
